version: "3"

services:
  datascience-notebook:
      container_name: datascience-notebook-container
      volumes:
        - ../source:/home/notebooks
      ports:
        - 8888:8888
      build:
        context: ./services/jupyter
        dockerfile: Dockerfile
